### ISSUE TITLE
[Meta] Quiz entity

### ISSUE THREAD

**Issue by and1truong** [atquizz/quiz.module#18]
https://www.drupal.org/node/2355375
## Basic entity
- [x] Define schema
- [x] Make sure quiz support revision
- [x] Define new permissions, callbacks.
- [x] Quiz entity link
- [x] Update quiz & question relationship [#54]
  - [x] Rename results.{nid,vid} [#76]
- [x] Missing language column in quiz [#82]
- [ ] Update views integration
## Quiz type entity
- [x] /admin/structure/quiz/add
- [x] /admin/structure/quiz/manage/%quiz_type/edit
- [x] /admin/structure/quiz/manage/%quiz_type/clone
- [x] /admin/structure/quiz/manage/%quiz_type/delete
- [x] /admin/structure/quiz/manage/%quiz_type/export
- [x] /admin/structure/quiz/manage/%quiz_type/fields
- [x] /admin/structure/quiz/manage/%quiz_type/display
- [x] Add QuizType.description [#38]
- [x] Add quiz type description at /quiz/add [#38]
- [x] Add QuizType.help [#39]
- [x] Display quiz type help text when user create new quiz. [#39]
### Quiz entity admin
- [x] /admin/content/quiz
- [ ] Views integration to /admin/content/quiz
  - [x] Created, Changed as date time
  - [x] View, Edit, Delete links [#46]
  - [ ] Add view access checking
### Quiz entity form [#19]
- [x] Define form
- [x] Validate
- [x] Submit
  - [x] Save quiz properties
  - [x] Check entity revision options
- [x] Implement hook_field_extra_fields()
- [x] If admin selects "Use the administration theme when editing or creating content" at /admin/appearance, use admin theme for /quiz/\* (admin pages).
- [x] If there's only one quiz type, /quiz/add is a form; If not, it should be a list of quiz type links.
- [x] Edit path for quiz entity should be /quiz/%/edit [#34]
- [x] On submit quiz entity form, redirect to /quiz/% if edit form is non-admin [#47]
- [x] Menu item /quiz/%/edit should be menu local task [#51]
- [x] Delete URL for quiz should be /quiz/%/delete [#48]
- [x] Provide delete link (fake button) for quiz entity form [#49]
- [x] /quiz/%/edit/questions [#56]
- [x] /quiz/%/revisions [#60, #68]
- [x] /quiz/%/results [#61]
- [x] /quiz/%/my-results [#63]
- [x] /quiz-result/% [#64, #65]
- [x] On delete quiz entity: Delete related content [#50]
- [x] Quiz entity form › Remember as global [#41]
- [x] Quiz entity form › Remember my settings [#42]
### Quiz entity view
- [x] /quiz/%quiz/view [#52]
- [x] Define controller for /quiz/%quiz_entity/take [#57]
- [x] Define controller for /quiz/%quiz_entity/take/%quiz_question [#59]
- [x] Define controller for /quiz/%quiz_entity/take/%quiz_question/feedback [#71]
- [x] Quiz taking navigation [#72]
### Update test cases
- [x]  Quiz Taking [#69]
- [x] Quiz Feedback [#71]
- [x] Quiz navigation/jumping [#72]
- [x] Quiz result [#73]
- [x] Short Answer
- [x] Scale
- [x] Quiz page
- [x] Multichoice
- [x] Matching
- [x] Long Answer
- [x] TrueFalse
### Others
- [x] [Bug] Quiz entity load is not working correctly [#20]
- [x] Define metadata for quiz entity [#31]
- [ ] Correct quiz access checking [#30]
- [x] Update quiz_stats.module to work with quiz entity [#75]
### Migrate [#80]
- [x] Implements hook_update_N() to update schema [#78]
- [x] Migrate quiz node to quiz entity [#79]
- [x] Apply path aliases rom quiz nodes to quiz entities [#81]
- [x] Quiz node body -> quiz entity body [#40]
- [x] Clean up migrate data
- [ ] If pathauto is enabled, has pattern for quiz node -> migrate pathauto pattern [#36]
## Related issues
- [x] Add {quiz_user_settings}.nid => type (quiz type)
- [x] Remove 'quiz' entity — Drop {quiz_node_properties} [#77]
- [x] Add redirect node/add/quiz => quiz/add [#17]
- [x] Add body field to all new quiz type [#16, #70]
- [x] Custom URI for each quiz type [#15 Postponed]
- [ ] Support pathauto module [#35]
- [ ] [Open/Close Date AND Time?](https://www.drupal.org/node/505676)
- [ ] [Quiz doesn't handle daylight savings time](https://www.drupal.org/node/1337758)
- [ ] Question settings per quiz type [#24]
- [x] Change tab title "Edit" to "Settings" at /admin/structure/quiz/manage/quiz [#25]
- [x] What's {quiz_terms}?
- [ ] Get rid of $_SESSION directly usage [#58]
- [ ] Rename {quiz_user_settings}.nid => qid
- [ ] Drop {quiz_user_settings} and related code.
- [ ] Is hook_quiz_view still needed? [#53]

**Comment by and1truong** [comment]
- /quiz/%/my-results is broken
- /quiz/2/results is broken
- Find and replace node_load(arg(1))
- Remove {questions_by_quiz}
- plugins/page_manager/tasks/quiztake.inc
