### ISSUE TITLE
[Sub-Meta] Quiz type entity

### ISSUE THREAD

**Issue by and1truong** [atquizz/quiz.module#33]
- [x] /admin/structure/quiz/add
- [x] /admin/structure/quiz/manage/%quiz_type/edit
- [x] /admin/structure/quiz/manage/%quiz_type/clone
- [x] /admin/structure/quiz/manage/%quiz_type/delete
- [x] /admin/structure/quiz/manage/%quiz_type/export
- [x] /admin/structure/quiz/manage/%quiz_type/fields
- [x] /admin/structure/quiz/manage/%quiz_type/display
- [ ] Add QuizType.description [#32]
  - [ ] Add quiz type description at /quiz/add
