### ISSUE TITLE
[Meta] Upgrade path

### ISSUE THREAD

**Issue by and1truong** [atquizz/quiz.module#80]
- [x] Implements hook_update_N() to update schema [#78]
- [x] Migrate quiz node to quiz entity [#79]
- [x] Apply path aliases rom quiz nodes to quiz entities [#81]
- [x] Quiz node body -> quiz entity body [#40]
- [x] Clean up migrate data
